"""Self-signed certificate generation and the server SSL context.

Every encrypted transport — DoT, DoH, DoQ and the admin console — starts by
calling `server_ssl_context`, and nothing in the suite called it: the key that
terminates all four was generated by untested code, including the `os.open`
that is the only thing keeping it off 0644.
"""
from __future__ import annotations

import ipaddress
import ssl
import stat

import pytest
from cryptography import x509

from trench.security.tls import ensure_cert, generate_self_signed, server_ssl_context


def _load(cert_path):
    return x509.load_pem_x509_certificate(cert_path.read_bytes())


def test_generate_writes_a_usable_pair(tmp_path):
    crt, key = tmp_path / "certs" / "t.crt", tmp_path / "certs" / "t.key"
    generate_self_signed(crt, key, ["dns.example.org"])
    assert crt.exists() and key.exists()
    cert = _load(crt)
    assert cert.subject.rfc4514_string() == "CN=dns.example.org"
    assert cert.issuer == cert.subject          # self-signed
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=str(crt), keyfile=str(key))    # must not raise


def test_the_private_key_is_never_world_readable(tmp_path):
    """The regression this guards: at the default umask the key landed 0644,
    so after the privilege drop any local account could impersonate the
    resolver."""
    crt, key = tmp_path / "t.crt", tmp_path / "t.key"
    generate_self_signed(crt, key)
    assert stat.S_IMODE(key.stat().st_mode) == 0o600


def test_regenerating_over_a_loose_existing_key_tightens_the_mode(tmp_path):
    crt, key = tmp_path / "t.crt", tmp_path / "t.key"
    key.write_bytes(b"stale")
    key.chmod(0o644)
    generate_self_signed(crt, key)
    assert stat.S_IMODE(key.stat().st_mode) == 0o600
    assert key.read_bytes() != b"stale"


def test_the_parent_directory_is_created(tmp_path):
    crt = tmp_path / "a" / "b" / "t.crt"
    generate_self_signed(crt, tmp_path / "a" / "b" / "t.key")
    assert crt.parent.is_dir()


def test_default_hostname_is_localhost(tmp_path):
    crt, key = tmp_path / "t.crt", tmp_path / "t.key"
    generate_self_signed(crt, key)
    san = _load(crt).extensions.get_extension_for_class(x509.SubjectAlternativeName)
    assert san.value.get_values_for_type(x509.DNSName) == ["localhost"]


def test_ip_hostnames_become_ip_sans_not_dns_sans(tmp_path):
    """A cert with `192.168.1.2` as a DNSName does not validate for that IP."""
    crt, key = tmp_path / "t.crt", tmp_path / "t.key"
    generate_self_signed(crt, key, ["dns.example.org", "192.168.1.2", "fd00::1"])
    san = _load(crt).extensions.get_extension_for_class(x509.SubjectAlternativeName)
    assert san.value.get_values_for_type(x509.DNSName) == ["dns.example.org"]
    assert san.value.get_values_for_type(x509.IPAddress) == [
        ipaddress.ip_address("192.168.1.2"), ipaddress.ip_address("fd00::1")]


def test_the_certificate_is_valid_now_and_not_a_ca(tmp_path):
    import datetime
    crt, key = tmp_path / "t.crt", tmp_path / "t.key"
    generate_self_signed(crt, key)
    cert = _load(crt)
    now = datetime.datetime.now(datetime.UTC)
    # Backdated, so a client whose clock is a minute behind still accepts it.
    assert cert.not_valid_before_utc < now < cert.not_valid_after_utc
    bc = cert.extensions.get_extension_for_class(x509.BasicConstraints)
    assert bc.value.ca is False and bc.critical is True


def test_ensure_cert_returns_operator_paths_untouched(tmp_path):
    crt, key = ensure_cert("/etc/ssl/my.crt", "/etc/ssl/my.key", tmp_path)
    assert str(crt) == "/etc/ssl/my.crt" and str(key) == "/etc/ssl/my.key"
    assert not (tmp_path / "certs").exists()


@pytest.mark.parametrize("cert,key", [(None, None), ("only.crt", None), (None, "only.key")])
def test_ensure_cert_generates_unless_both_are_given(tmp_path, cert, key):
    crt_path, key_path = ensure_cert(cert, key, tmp_path)
    assert crt_path == tmp_path / "certs" / "trench.crt"
    assert key_path == tmp_path / "certs" / "trench.key"
    assert crt_path.exists() and key_path.exists()


def test_ensure_cert_reuses_an_existing_pair(tmp_path):
    first_crt, first_key = ensure_cert(None, None, tmp_path)
    before = (first_crt.read_bytes(), first_key.read_bytes())
    again = ensure_cert(None, None, tmp_path)
    assert (again[0].read_bytes(), again[1].read_bytes()) == before


def test_a_half_present_pair_is_regenerated(tmp_path):
    crt, key = ensure_cert(None, None, tmp_path)
    key.unlink()
    ensure_cert(None, None, tmp_path)
    assert key.exists() and crt.exists()


def test_server_ssl_context_sets_alpn_and_a_tls_floor(tmp_path):
    ctx = server_ssl_context(None, None, data_dir=tmp_path, alpn=["dot"])
    assert isinstance(ctx, ssl.SSLContext)
    assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2
    assert ctx.verify_mode == ssl.CERT_NONE       # a server does not demand client certs


def test_server_ssl_context_without_alpn(tmp_path):
    ctx = server_ssl_context(None, None, data_dir=tmp_path, alpn=[])
    assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2


def test_server_ssl_context_negotiates_the_advertised_alpn(tmp_path):
    """ALPN is not decoration: DoH over h2 and DoQ both fail without it."""
    import socket
    import threading
    server_ctx = server_ssl_context(None, None, data_dir=tmp_path,
                                    alpn=["h2", "http/1.1"])
    client_ctx = ssl.create_default_context()
    client_ctx.check_hostname = False
    client_ctx.verify_mode = ssl.CERT_NONE
    client_ctx.set_alpn_protocols(["h2"])

    lsock = socket.socket()
    lsock.bind(("127.0.0.1", 0))
    lsock.listen(1)
    negotiated = []

    def serve():
        conn, _ = lsock.accept()
        try:
            with conn, server_ctx.wrap_socket(conn, server_side=True) as tls:
                negotiated.append(tls.selected_alpn_protocol())
        except OSError:
            negotiated.append(None)

    t = threading.Thread(target=serve, daemon=True)
    t.start()
    with socket.create_connection(lsock.getsockname()) as sock, \
            client_ctx.wrap_socket(sock, server_hostname="localhost") as tls:
        assert tls.selected_alpn_protocol() == "h2"
    t.join(5)
    lsock.close()
    assert negotiated == ["h2"]


def test_server_ssl_context_uses_operator_supplied_files(tmp_path):
    crt, key = tmp_path / "own.crt", tmp_path / "own.key"
    generate_self_signed(crt, key, ["own.example.org"])
    ctx = server_ssl_context(str(crt), str(key), data_dir=tmp_path, alpn=["dot"])
    assert isinstance(ctx, ssl.SSLContext)
    # Nothing was minted alongside it.
    assert not (tmp_path / "certs").exists()
